spring:
  application:
    name: notification-service

#  data:
#    mongodb:
#      uri: mongodb://${MONGO_USERNAME:mongo}:${MONGO_PASSWORD:mongo}@${MONGO_HOST:localhost:27017}/${MONGO_DATABASE:mongodb}?authSource=${MONGO_AUTH_SOURCE:admin}

  profiles:
    active: prod
  config:
    import: "configserver:"
  cloud:
    config:
      uri: ${CONFIG_SERVER_URL:http://127.0.0.1:8889}
