spring:
  application:
    name: config-server

  profiles:
    active: composite
  cloud:
    config:
      server:
        composite:
          - type: git
            uri: https://github.com/Art-Vanndeth/vault-micro-payment-platform-configuration.git
            search-paths: 'services'
            default-label: main
            clone-on-start: true
          - type: vault
            host: localhost
            port: 8200
            scheme: http
            backend: config
            kv-version: 2
            profile-separator: '/'
            default-application: micro-payment
        default-application-name: default
        default-profile: default
    vault:
      token: ${VAULT_TOKEN:dev-root-token} # Replace with your actual Vault token

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8887/eureka/

server:
  port: 8889

logging:
  level:
    org.springframework.cloud.config: DEBUG
    org.springframework.vault: DEBUG
