spring:
  application:
    name: payment-service

  r2dbc:
    url: r2dbc:postgresql://127.0.0.1:5432/payment_platform
    username: payment_user
    password: payment_password
    pool:
      initial-size: 10
      max-size: 20

  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: payment-service-group

integration:
  account-service:
    url: http://localhost:8090/api/accounts

server:
  port: 8091

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

kafka:
  topics:
    payment-created-events: payment-created-events
    payment-events: payment-events