spring:
  application:
    name: config-server

  profiles:
    active: git,vault
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Art-Vanndeth/vault-micro-payment-platform-configuration.git
          search-paths: '/services/**'
          default-label: main
        vault:
          host: localhost
          port: 8200
          scheme: http
          authentication: TOKEN
          token: dev-root-token
          kv-version: 2

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8887/eureka/

server:
  port: 8889
